name: check_versions
on:
  workflow_dispatch:
  schedule:
  - cron: 0 0 * * 0     # weekly

permissions: {}

jobs:
  check_pytorch_version:
    runs-on: ubuntu-latest
    name: Check binder-installed pytorch version
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 #v6.2.0
    - run: |
        recent_version=$(pip index versions torch | grep -oE "torch \([0-9\.]*?" | sed 's/torch (//g')
        pipfile_version=$(python .github/workflows/check_torch_version.py Pipfile)
        if [[ $pipfile_version != $recent_version ]]; then
            echo "PYTORCH VERSION CHANGED, update Pipfile";
            echo "Pipfile: $pipfile_version";
            echo "PyPI: $recent_version";
            exit 1;
        fi

  check_plenoptic_dependencies:
    runs-on: ubuntu-latest
    name: Check binder-installed dependencies against plenoptic
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 #v6.2.0
    - run: |
        echo "Downloading toml from https://raw.githubusercontent.com/plenoptic-org/plenoptic/refs/heads/main/pyproject.toml"
        curl https://raw.githubusercontent.com/plenoptic-org/plenoptic/refs/heads/main/pyproject.toml > plenoptic.toml
        python .github/workflows/check_packages.py plenoptic.toml Pipfile
